### PR TITLE
Fix compatibility with PHPUnit 10.4

### LINKED ISSUE #46: Stub::make() seems to be broken when using PHPUnit 10.4
`Stub::make(\DateTime::class);` results in the following error:

```
PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class PHPUnit\Framework\MockObject\Generator\Generator does not have a method "getMock" in /var/www/html/vendor/codeception/stub/src/Stub.php:455
Stack trace:
#0 /var/www/html/vendor/codeception/stub/src/Stub.php(455): call_user_func_array(Array, Array)
#1 /var/www/html/vendor/codeception/stub/src/Stub.php(418): Codeception\Stub::doGenerateMock(Array)
#2 /var/www/html/vendor/codeception/stub/src/Stub.php(91): Codeception\Stub::generateMock('DateTime', NULL, Array, '', false, false)
#3 /var/www/html/tests/Unit/Entity/DcsCheckCest.php(49): Codeception\Stub::make('DateTime')
```

Seems like https://github.com/sebastianbergmann/phpunit/commit/614a52a9cceee88e5b683d60029e0baaa9d95a62 renamed the method `Generator::getMock()` to `testDouble()`.

### PR DESCRIPTION
**Pull request by W0rma**
Fixes https://github.com/Codeception/Stub/issues/46

### CODE REVIEW

File: src/Stub.php [hunk 1]
```diff
@@ -415,7 +415,12 @@ public static function constructEmptyExcept(
 
     private static function generateMock()
     {
-        return self::doGenerateMock(func_get_args());
+        $args = func_get_args();
+        if (version_compare(PHPUnitVersion::series(), '10.4', '>=') && !is_bool($args[1])) {
+            array_splice($args, 1, 0, [true]);
```
Comment (W0rma) [inline src/Stub.php:420]: https://github.com/sebastianbergmann/phpunit/commit/c8e2aa0c54770f1124013d2b4ecc61eebc6aa98b added a new parameter to `Generator::testDouble()`

File: src/Stub.php [hunk 2]
```diff
@@ -433,26 +438,28 @@ private static function generateMockForAbstractClass(): object
     private static function doGenerateMock($args, $isAbstract = false)
     {
         $testCase = self::extractTestCaseFromArgs($args);
-        $methodName = $isAbstract ? 'getMockForAbstractClass' : 'getMock';
+
+        // PHPUnit 10.4 changed method names
+        if (version_compare(PHPUnitVersion::series(), '10.4', '>=')) {
+            $methodName = $isAbstract ? 'mockObjectForAbstractClass' : 'testDouble';
```
Comment (W0rma) [inline src/Stub.php:444]: https://github.com/sebastianbergmann/phpunit/issues/5241 deprecated `mockObjectForAbstractClass`.
Seems like it will still be available in PHPUnit 11 but will be dropped in PHPUnit 12.
